python -u train_continual_lora.py --mlp '140,512,5' \
    --batch_size 128 \
    --epoch 60 \
    --lr 0.05 \
    --Tw 10 \
    --num_selected_speakers_continue 7\
    --num_selected_speakers_pretrained 5\
    --continue_learn_idx 6\
    --previous_unlearn_idx 1\
    --n_bins 5 \
    --name 'snn_lsm_512_continue_5cls_10tw' \
    --lora_rank_continue 8\
    --lora_alpha_continue 16 \
    --lora_rank_pretrained 8\
    --lora_alpha_pretrained 16\
    --pretrained_model './checkpoints_randlabel_unlearn/snn_lsm_512_randlabel_5cls_10twat57.pth'